apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args: ["server", "/data", "--console-address", ":9001"]
        env:
        - name: MINIO_ROOT_USER
          value: "minioadmin"
        - name: MINIO_ROOT_PASSWORD
          value: "minioadmin"
        - name: MINIO_SERVER_URL
          value: "http://minio:9000" # Internal Service
        - name: MINIO_BROWSER_REDIRECT_URL
          value: "http://minio:9001" # Internal Service
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
spec:
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  selector:
    app: minio

---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-buckets
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: create-buckets
        image: minio/mc:latest
        command: ["/bin/bash", "/scripts/create-buckets.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: scripts
        configMap:
          name: minio-scripts
          defaultMode: 0777
