apiVersion: apps/v1
kind: Deployment
metadata:
  name: polynote
  namespace: default
  labels:
    app: polynote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polynote
  template:
    metadata:
      labels:
        app: polynote
        spark-role: driver
    spec:
      serviceAccountName: jupyterhub  # Reuse SA
      initContainers:
        - name: spark-home-init
          image: $(SPARK_IMAGE)
          imagePullPolicy: Always
          command: ["sh", "-c", "cp -r /opt/spark/* /mnt/spark/ && chown -R 1000:100 /mnt/spark"]
          volumeMounts:
            - name: spark-home
              mountPath: /mnt/spark
      containers:
        - name: polynote
          image: $(POLYNOTE_IMAGE)
          imagePullPolicy: Always
          ports:
            - containerPort: 8192
              name: web
            - containerPort: 4040
              name: spark-ui
          env:
            - name: SPARK_HOME
              value: "/opt/spark"
            - name: SPARK_DRIVER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MINIO_ENDPOINT
              value: "$(MINIO_ENDPOINT)"
            - name: AWS_ACCESS_KEY_ID
              value: "$(AWS_ACCESS_KEY_ID)"
            - name: AWS_SECRET_ACCESS_KEY
              value: "$(AWS_SECRET_ACCESS_KEY)"
          volumeMounts:
            - name: spark-home
              mountPath: /opt/spark
            - name: spark-config
              mountPath: /tmp/spark-config-template/spark-defaults.conf
              subPath: spark-defaults.conf
            - name: polynote-config
              mountPath: /opt/polynote/config.yml
              subPath: config.yml
      volumes:
        - name: spark-home
          emptyDir: {}
        - name: spark-config
          configMap:
            name: spark-config
        - name: polynote-config
          configMap:
            name: polynote-config
---
apiVersion: v1
kind: Service
metadata:
  name: polynote
  namespace: default
spec:
  selector:
    app: polynote
  ports:
    - protocol: TCP
      port: 8192
      targetPort: 8192
      name: web
    - protocol: TCP
      port: 4040
      targetPort: 4040
      name: spark-ui
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: polynote-driver
  namespace: default
spec:
  clusterIP: None
  selector:
    app: polynote
  ports:
    - port: 22321
      name: spark-driver
    - port: 22322
      name: spark-blockmanager
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: polynote-config
  namespace: default
data:
  config.yml: |
    listen:
      host: 0.0.0.0
      port: 8192
    storage:
      base_dir: notebooks
    spark:
      master: k8s://https://kubernetes.default.svc
      conf:
        spark.kubernetes.container.image: $(SPARK_IMAGE)
        spark.driver.host: $(SPARK_DRIVER_HOST)
        spark.driver.bindAddress: 0.0.0.0
        spark.kubernetes.authenticate.driver.serviceAccountName: jupyterhub
        spark.hadoop.fs.s3a.endpoint: $(MINIO_ENDPOINT)
        spark.hadoop.fs.s3a.access.key: $(AWS_ACCESS_KEY_ID)
        spark.hadoop.fs.s3a.secret.key: $(AWS_SECRET_ACCESS_KEY)
        spark.hadoop.fs.s3a.path.style.access: "true"
        spark.hadoop.fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
