apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeppelin
  namespace: default
  labels:
    app: zeppelin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeppelin
  template:
    metadata:
      labels:
        app: zeppelin
        spark-role: driver
    spec:
      # Init Container: Copies Spark binaries to /spark to standardise paths
      initContainers:
        - name: spark-home-init
          image: ${SPARK_IMAGE}
          imagePullPolicy: Always
          command: ["sh", "-c", "cp -r /opt/spark/* /spark/ && mkdir -p /spark/event_logs && chmod 777 /spark/event_logs"]
          volumeMounts:
            - name: spark-home
              mountPath: /spark

      containers:
        - name: zeppelin
          image: ${ZEPPELIN_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
            - containerPort: 4040
              name: spark-ui
          env:
            # Network Configuration
            - name: SPARK_DRIVER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPARK_LOCAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPARK_DRIVER_BIND_ADDRESS
              value: "0.0.0.0"
            - name: ZEPPELIN_PORT
              value: "8080"
            - name: ZEPPELIN_ADDR
              value: "0.0.0.0"
            - name: ZEPPELIN_MEM
              value: "-Xms1024m -Xmx2048m -XX:MaxMetaspaceSize=512m"

            # S3 Notebook Storage (MinIO)
            - name: ZEPPELIN_NOTEBOOK_STORAGE
              value: "org.apache.zeppelin.notebook.repo.S3NotebookRepo"
            - name: ZEPPELIN_NOTEBOOK_S3_ENDPOINT
              value: "http://minio.default.svc.cluster.local:9000"
            - name: ZEPPELIN_NOTEBOOK_S3_BUCKET
              value: "notebooks"
            - name: ZEPPELIN_NOTEBOOK_S3_USER
              value: "minioadmin"
            - name: ZEPPELIN_NOTEBOOK_S3_PATH_STYLE_ACCESS
              value: "true"
            - name: AWS_ACCESS_KEY_ID
              value: "minioadmin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "minioadmin"

            # Spark Path Configuration (Server side)
            - name: SPARK_HOME
              value: "/spark"

            - name: ZEPPELIN_K8S_CONTAINER_IMAGE
              value: "${ZEPPELIN_IMAGE}"
            - name: ZEPPELIN_K8S_SPARK_CONTAINER_IMAGE
              value: "${SPARK_IMAGE}"
            - name: ZEPPELIN_K8S_SPARK_HOME
              value: "/spark"
            - name: ZEPPELIN_K8S_CONTAINER_IMAGE_PULL_POLICY
              value: "Always" # Forces fresh pull to bypass stale node caches
            - name: ZEPPELIN_K8S_SERVICE_ACCOUNT
              value: "zeppelin-server" # Grant permissions for Driver Pods (Interpreters) to create Executors

            # Lifecycle Management (Auto-Shutdown)
            - name: ZEPPELIN_INTERPRETER_LIFECYCLEMANAGER_CLASS
              value: "org.apache.zeppelin.interpreter.lifecycle.TimeoutLifecycleManager"
            - name: ZEPPELIN_INTERPRETER_LIFECYCLEMANAGER_TIMEOUT_THRESHOLD
              value: "600000"

            # Spark Version Check (Disable for Spark 4.x compatibility)
            - name: ZEPPELIN_SPARK_ENABLESUPPORTEDVERSIONCHECK
              value: "false"

          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"

          volumeMounts:
            # Mount custom Spark config (disables event logs, etc.)
            - name: spark-config
              mountPath: /spark/conf/spark-defaults.conf
              subPath: spark-defaults.conf
            # Mount custom Zeppelin Config (Lifecycle Manager)
            - name: zeppelin-site
              mountPath: /opt/zeppelin/conf/zeppelin-site.xml
              subPath: zeppelin-site.xml
            # Shared volume for Spark binaries
            - name: spark-home
              mountPath: /spark
            # Pod Templates for Interpreters
            - name: interpreter-template
              mountPath: /opt/zeppelin/k8s/interpreter-template.yaml
              subPath: interpreter-template.yaml
            - name: executor-template
              mountPath: /opt/zeppelin/k8s/executor-template.yaml
              subPath: executor-template.yaml
            # MOUNT OVERRIDE FOR DEFAULT SPEC
            - name: interpreter-spec
              mountPath: /opt/zeppelin/k8s/interpreter/100-interpreter-spec.yaml
              subPath: interpreter-spec.yaml
            # Overwrite Spark Interpreter Setting Defaults
            - name: spark-setting
              mountPath: /opt/zeppelin/interpreter/spark/interpreter-setting.json
              subPath: interpreter-setting.json

      serviceAccountName: zeppelin-server
      volumes:
        - name: spark-config
          configMap:
            name: spark-config
        - name: zeppelin-site
          configMap:
            name: zeppelin-site
        # ConfigMaps for Templates
        - name: interpreter-template
          configMap:
            name: spark-templates
        - name: executor-template
          configMap:
            name: spark-templates
        - name: interpreter-spec
          configMap:
            name: zeppelin-interpreter-spec
        - name: spark-setting
          configMap:
            name: zeppelin-spark-setting
        - name: spark-home
          emptyDir: {}
---
# Main Service for Accessing Zeppelin UI
apiVersion: v1
kind: Service
metadata:
  name: zeppelin
  namespace: default
spec:
  selector:
    app: zeppelin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web
    - protocol: TCP
      port: 4040
      targetPort: 4040
      name: spark-ui
  type: ClusterIP
---
# Headless Service for Internal RPC Communication
apiVersion: v1
kind: Service
metadata:
  name: zeppelin-server
  namespace: default
spec:
  clusterIP: None
  selector:
    app: zeppelin
  ports:
    - port: 12323
      name: rpc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeppelin-server
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zeppelin-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: zeppelin-server
    namespace: default
