apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-service-monitor
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  jobLabel: spark-role
  selector:
    matchLabels:
      app: spark-ui-headless
  endpoints:
  - port: spark-ui
    path: /metrics/prometheus/
    interval: 10s
    honorLabels: true
  namespaceSelector:
    matchNames:
      - default
