apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-monitor
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  jobLabel: spark-app
  selector:
    matchExpressions:
      - {key: spark-role, operator: In, values: [driver]}
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: spark-ui
    path: /metrics/prometheus
    interval: 10s
    honorLabels: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zeppelin-monitor
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: zeppelin
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: spark-ui
    path: /metrics/prometheus
    interval: 10s
